# Generated by Django 2.2.4 on 2020-12-15 15:46

import phonenumbers
from django.db import migrations


def fill_owner_pure_phone(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        phone_number = flat.owners_phonenumber
        normalized_phone = phonenumbers.parse(phone_number, 'RU')
        if phonenumbers.is_valid_number(normalized_phone):
            flat.owner_pure_phone = normalized_phone
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone)
    ]
