# Generated by Django 2.2.4 on 2020-12-17 08:16

from django.db import migrations


def fill_owners_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(full_name=flat.owner, pure_phone=flat.owner_pure_phone, phonenumber=flat.owners_phonenumber)
        owner[0].flats.add(flat)
        owner[0].save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20201216_1310'),
    ]

    operations = [
        migrations.RunPython(fill_owners_from_flat)
    ]
