# Generated by Django 2.2.4 on 2020-12-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201217_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='deprecated_owner',
        ),
    ]
